version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install -g expo-cli
      - npm install

  pre_build:
    commands:
      - echo "Setting Expo static bundler..."
      - export EXPO_USE_STATIC_WEBPACK_CONFIG=1

  build:
    commands:
      - echo "Exporting static web build..."
      - npx expo export --platform web --output-dir web-build

  post_build:
    commands:
      - echo "Expo web export complete."

artifacts:
  base-directory: web-build
  files:
    - '**/*'
