version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # or 20 if supported by CodeBuild
    commands:
      - echo Installing Node dependencies...
      - npm install -g expo-cli
      - npm install

  pre_build:
    commands:
      - echo Logging in to AWS...
      # Add any AWS CLI setup here if needed (e.g., S3, ECR)
      - echo Starting build process...

  build:
    commands:
      # Choose one of the following based on your target:
      
      # For Web:
      - echo Building Expo Web App...
      - npx expo export:web

      # For Android (comment out if not needed):
      # - echo Building Android App...
      # - npx expo build:android --non-interactive

      # For iOS (comment out if not needed):
      # - echo Building iOS App...
      # - npx expo build:ios --non-interactive

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: web-build  # or 'dist' if using a different build output folder (adjust accordingly)
